config/routes.rb
Rails.application.routes.draw do
  devise_for :users  # Rota para o Devise

  root to: 'home#index'  # Página inicial será a listagem de produtos

  # Dashboard
  get 'dashboard', to: 'dashboard#show'

  get "categories", to: "categories#index"


  # Account (usuário)
  resource :account, only: [:show, :edit, :update]

  # Ads (Anúncios)
  resources :ads, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get 'review',          to: 'ads#review'
      put 'publish',         to: 'ads#publish'
      put 'deactivate',      to: 'ads#deactivate'
      post 'add_image',      to: 'ads#add_image'
      patch 'sort_images',   to: 'ads#sort_images'
      delete 'remove_image', to: 'ads#remove_image'
    end
  end

  # Products (Produtos)
  resources :products do
    collection do
      get :dynamic_fields
      get :load_subcategories
    end
  end

  # Categories (Categorias)
  resources :categorias, only: [:index] do
    member do
      get :subcategorias
    end
  end
  

  # Messages (Mensagens)
  resources :messages, only: [:index, :show, :new, :create, :destroy]

  # Bookmarks (Favoritos)
  resources :bookmarks, only: [:index, :create, :destroy]

  # Locations (NPA) - Ajuste para evitar conflitos
  resources :locations, only: [:index, :show]

  # Results (Resultados)
  resources :results, only: [:index]

  # Language - Alteração de idioma
  post 'change_locale', to: 'application#change_locale'

  # Páginas estáticas (Help, Rules, Terms, Conditions)
  get 'help',       to: 'pages#help'
  get 'rules',      to: 'pages#rules'
  get 'terms',      to: 'pages#terms'
  get 'conditions', to: 'pages#conditions'

  # Ajustando rotas de locations que eram conflitantes
  get '/locations/new',    to: 'locations#new', as: :new_location
  post '/locations',       to: 'locations#create', as: :create_location
  patch '/locations/:id',  to: 'locations#update', as: :update_location
  delete '/locations/:id', to: 'locations#destroy', as: :destroy_location
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many_attached :gallery_images

  validates :title, presence: true, length: { minimum: 10, maximum: 79 }
  validates :description, presence: true, length: { minimum: 50, maximum: 2000 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :ads
  
  validates :name, presence: true, uniqueness: true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 100 }
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :stock, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :ads, dependent: :destroy
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
  end

  def edit
  end

  def update
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @ads = Ad.all
  end

  def show
    @ad = Ad.find(params[:id])
  end

  def new
    @ad = Ad.new
  end

  def create
    @ad = current_user.ads.build(ad_params)
    if @ad.save
      redirect_to @ad, notice: 'Anúncio criado com sucesso.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @ad = Ad.find(params[:id])
  end

  def update
    @ad = Ad.find(params[:id])
    if @ad.update(ad_params)
      redirect_to @ad, notice: 'Anúncio atualizado com sucesso.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @ad = Ad.find(params[:id])
    @ad.destroy
    redirect_to ads_path, notice: 'Anúncio excluído com sucesso.'
  end

  private

  def ad_params
    params.require(:ad).permit(:title, :description, :price, :category_id, gallery_images: [])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def help
  end

  def rules
  end

  def terms
  end

  def conditions
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: "Produto criado com sucesso!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def dynamic_fields
    @category = Category.find(params[:category_id])
    @fields = @category.category_fields

    respond_to do |format|
      format.html { render partial: "products/dynamic_fields", locals: { fields: @fields } }
    end
  end

  def load_subcategories
    @subcategories = Category.where(parent_id: params[:category_id])
  
    respond_to do |format|
      format.html { render partial: "products/subcategories", locals: { subcategories: @subcategories } }
    end
  end  

  private

  def product_params
    params.require(:product).permit(:title, :description, :category_id, :price, :images_count)
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/products/_dynamic_fields.html.erb
<% fields.each do |field| %>
  <div class="field">
    <%= label_tag field.name, field.name.humanize %>
    
    <% if field.input_type == "text" %>
      <%= text_field_tag field.name, nil, placeholder: field.placeholder, class: "form-control" %>

    <% elsif field.input_type == "select" %>
      <%= select_tag field.name, options_for_select(field.options), class: "form-control" %>

    <% elsif field.input_type == "checkbox" %>
      <% field.options.each do |option| %>
        <div class="form-check">
          <%= check_box_tag "#{field.name}[]", option, false, class: "form-check-input" %>
          <%= label_tag "#{field.name}_#{option}", option, class: "form-check-label" %>
        </div>
      <% end %>

    <% elsif field.input_type == "radio" %>
      <% field.options.each do |option| %>
        <div class="form-check">
          <%= radio_button_tag field.name, option, false, class: "form-check-input" %>
          <%= label_tag "#{field.name}_#{option}", option, class: "form-check-label" %>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/products/_form.html.erb
<div data-controller="category-fields">
  <div class="field">
    <%= f.label :category_id, "Categoria Principal" %>
    <%= f.collection_select :category_id, Category.where(parent_id: nil), :id, :name, { prompt: "Selecione uma categoria" }, class: "form-control", data: { action: "change->category-fields#loadSubcategories" } %>
  </div>

  <div id="subcategory-container" data-category-fields-target="subcategoryContainer"></div>
</div>

<!-- Campos do produto (inicialmente ocultos) -->
<div id="product-fields" style="display: none;">
  <h3>Detalhes do Produto</h3>

  <div class="field">
    <%= f.label :title, "Título do Produto" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :description, "Descrição" %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <!-- Campos dinâmicos para categorias -->
  <div id="dynamic-fields" data-category-fields-target="dynamicFields"></div>

  <div class="field">
    <%= f.label :price, "Preço" %>
    <%= f.number_field :price, step: 0.01, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.submit "Salvar Produto", class: "btn btn-primary" %>
  </div>
</div>

<!-- Dropdown para categorias no menu -->
<ul id="category-menu" class="dropdown-menu"></ul>

app/views/products/_subcategories.html.erb
<% if subcategories.any? %>
  <div class="field">
    <label for="subcategory">Subcategoria</label>
    <select id="subcategory" class="form-control" data-action="change->category-fields#loadSubcategories">
      <option value="">Selecione uma subcategoria</option>
      <% subcategories.each do |subcategory| %>
        <option value="<%= subcategory.id %>"><%= subcategory.name %></option>
      <% end %>
    </select>
  </div>
  <div id="subcategory-container"></div>
<% else %>
  <script>
    document.getElementById("product-fields").style.display = "block";
  </script>
<% end %>

app/views/products/index.html.erb
<h1>INDEX DE PRODUTOS</h1>

<ul>
  <% @products.each do |product| %>
    <li><%= product.name %> - <%= product.price %></li>
  <% end %>
</ul>

<%#= form_with(url: change_locale_path, method: :post) do |form| %>
  <%#= form.select :locale, [['Français', 'fr'], ['Deutsch', 'de'], ['Italiano', 'it']], {}, onchange: 'this.form.submit();' %>
<%# end %>

app/views/products/new.html.erb
<h1>Novo Produto</h1>

<%= form_with(model: @product, local: true) do |f| %>
  <%= render 'form', f: f %>
<% end %>


<%#= link_to "Voltar", products_path, class: "btn btn-secondary" %>