config/routes.rb
Rails.application.routes.draw do
  devise_for :users  # Rota para o Devise

  root to: 'home#index'  # Página inicial será a listagem de produtos

  # Dashboard
  get 'dashboard', to: 'dashboard#show'

  get "categories", to: "categories#index"


  # Account (usuário)
  resource :account, only: [:show, :edit, :update]

  # Ads (Anúncios)
  resources :ads, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get 'review',          to: 'ads#review'
      put 'publish',         to: 'ads#publish'
      put 'deactivate',      to: 'ads#deactivate'
      post 'add_image',      to: 'ads#add_image'
      patch 'sort_images',   to: 'ads#sort_images'
      delete 'remove_image', to: 'ads#remove_image'
    end
  end

  # Products (Produtos)
  resources :products do
    collection do
      get :dynamic_fields
      get :load_subcategories
    end
  end

  # Categories (Categorias)
  resources :categorias, only: [:index] do
    member do
      get :subcategorias
    end
  end
  

  # Messages (Mensagens)
  resources :messages, only: [:index, :show, :new, :create, :destroy]

  # Bookmarks (Favoritos)
  resources :bookmarks, only: [:index, :create, :destroy]

  # Locations (NPA) - Ajuste para evitar conflitos
  resources :locations, only: [:index, :show]

  # Results (Resultados)
  resources :results, only: [:index]

  # Language - Alteração de idioma
  post 'change_locale', to: 'application#change_locale'

  # Páginas estáticas (Help, Rules, Terms, Conditions)
  get 'help',       to: 'pages#help'
  get 'rules',      to: 'pages#rules'
  get 'terms',      to: 'pages#terms'
  get 'conditions', to: 'pages#conditions'

  # Ajustando rotas de locations que eram conflitantes
  get '/locations/new',    to: 'locations#new', as: :new_location
  post '/locations',       to: 'locations#create', as: :create_location
  patch '/locations/:id',  to: 'locations#update', as: :update_location
  delete '/locations/:id', to: 'locations#destroy', as: :destroy_location
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many_attached :gallery_images

  validates :title, presence: true, length: { minimum: 10, maximum: 79 }
  validates :description, presence: true, length: { minimum: 50, maximum: 2000 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :ads
  
  validates :name, presence: true, uniqueness: true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 100 }
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :stock, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :ads, dependent: :destroy
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
  end

  def edit
  end

  def update
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @ads = Ad.all
  end

  def show
    @ad = Ad.find(params[:id])
  end

  def new
    @ad = Ad.new
  end

  def create
    @ad = current_user.ads.build(ad_params)
    if @ad.save
      redirect_to @ad, notice: 'Anúncio criado com sucesso.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @ad = Ad.find(params[:id])
  end

  def update
    @ad = Ad.find(params[:id])
    if @ad.update(ad_params)
      redirect_to @ad, notice: 'Anúncio atualizado com sucesso.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @ad = Ad.find(params[:id])
    @ad.destroy
    redirect_to ads_path, notice: 'Anúncio excluído com sucesso.'
  end

  private

  def ad_params
    params.require(:ad).permit(:title, :description, :price, :category_id, gallery_images: [])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @locations = current_user.locations
    flash[:notice] = t('locations.index_message')  # Exemplo de tradução em uma ação
  end

  def new
    @location = current_user.locations.new
  end

  def create
    @location = current_user.locations.new(location_params)
    if @location.save
      redirect_to locations_path, notice: 'Endereço salvo com sucesso.'
    else
      render :new
    end
  end

  def edit
    @location = current_user.locations.find(params[:id])
  end

  def update
    @location = current_user.locations.find(params[:id])
    if @location.update(location_params)
      redirect_to locations_path, notice: 'Endereço atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @location = current_user.locations.find(params[:id])
    @location.destroy
    redirect_to locations_path, notice: 'Endereço excluído com sucesso.'
  end

  private

  def location_params
    params.require(:location).permit(:street, :number, :npa, :canton)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def help
  end

  def rules
  end

  def terms
  end

  def conditions
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/locations/edit.html.erb
<h1>Editar Endereço</h1>

<%= form_with model: @location, local: true do |form| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "erro") %> proibiu este endereço de ser salvo:</h2>
      <ul>
        <% @location.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>

  <div>
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div>
    <%= form.label :npa %>
    <%= form.text_field :npa %>
  </div>

  <div>
    <%= form.label :canton %>
    <%= form.text_field :canton %>
  </div>

  <div>
    <%= form.submit 'Atualizar Endereço' %>
  </div>
<% end %>

<%= link_to 'Voltar', locations_path %>

app/views/locations/index.html.erb
<h1>Meus Endereços</h1>

<%= link_to 'Adicionar Novo Endereço', new_location_path %>

<ul>
  <% @locations.each do |location| %>
    <li>
      <%= location.street %>, <%= location.number %> - <%= location.npa %> - <%= location.canton %>
      <%= link_to 'Editar', edit_location_path(location) %> |
      <%= link_to 'Excluir', location_path(location), method: :delete %>
    </li>
  <% end %>
</ul>

app/views/locations/new.html.erb
<h1>Adicionar Novo Endereço</h1>

<%= form_with model: @location, local: true do |form| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "erro") %> proibiu este endereço de ser salvo:</h2>
      <ul>
        <% @location.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>

  <div>
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div>
    <%= form.label :npa %>
    <%= form.text_field :npa %>
  </div>

  <div>
    <%= form.label :canton %>
    <%= form.text_field :canton %>
  </div>

  <div>
    <%= form.submit 'Salvar Endereço' %>
  </div>
<% end %>

<%= link_to 'Voltar', locations_path %>

app/views/locations/show.html.erb
<h1>Endereço</h1>

<p><strong>Rua:</strong> <%= @location.street %></p>
<p><strong>Número:</strong> <%= @location.number %></p>
<p><strong>NPA:</strong> <%= @location.npa %></p>
<p><strong>Cantão:</strong> <%= @location.canton %></p>

<%= link_to 'Voltar', locations_path %> |
<%= link_to 'Editar', edit_location_path(@location) %>